### PR TITLE
various improvements (/bin/sh, respect pictures dir, remove xterm dependency, use maim...)

### PR DESCRIPTION
**Pull request by ralsei**
listen man i'm sorry but this is the most horrible code i've ever seen like i thought i was bad but holy FUCK

### CODE REVIEW

**Comment by ralsei** [comment]
(also note that maim is better than gnome-screenshot as it doesn't depend on gnome)

**Comment by thebitstick** [comment]
``` bash
Makoto :: ~/ShareXin ‹ix-master› % sh Full.sh                                  
cp: cannot create regular file ‘~/Pictures/sharexin/twitter-2016-03-23-17:50:17.png’: No such file or directory
Full.sh: 19: Full.sh: Full.sh/term.sh: not found
```

**Comment by ralsei** [comment]
did you install maim?

**Comment by thebitstick** [comment]
Yes I did
and slop

**Comment by thebitstick** [comment]
No change
Same result

**Comment by ralsei** [comment]
`mkdir ~/Pictures/sharexin`

**Comment by thebitstick** [comment]
I already have done that

**Comment by ralsei** [comment]
forgot that `~` doesn't expand in quotes

**Comment by thebitstick** [comment]
Not uploading for some reason.
Captures screenshot, and launches Python script, but doesn't upload.

**Comment by thebitstick** [comment]
I confirmed that when launching term.sh (whatever terminal launches), the `$image` variable doesn't export to that Terminal

**Comment by ralsei** [comment]
Well, yeah; that's unavoidable, they're running in different shell processes. Probably fix your script.

**Comment by thebitstick** [comment]
1. Shouldn't `export image` bring the variable out
2. I have no idea how to fix it

**Comment by ralsei** [comment]
no

try to write it to a file, perhaps /tmp/sharexin_img, then read from the file rather than using the var

**Comment by thebitstick** [comment]
That might work, I'll try it

**Pull request merged**
